apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 127003514485.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 127003514485.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 22475c85
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
